[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai>=1.93.0",
    "pandas>=2.3.0",
    "praw>=7.8.1",
    "requests>=2.32.4",
    "streamlit>=1.46.1",
]
